# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Maven repository caching
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
    - name: Load dependencies with pom-libs.xml
      run: mvn -B install --file pom-libs.xml
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          sphinx==1.8.5
    - name: Build docs with sphinx
      run: mvn install -B -f docs/pom.xml -Dtycho.mode=maven -Pdocs
    - name: Run uDig product & sdk build with tests
      uses: GabrielBB/xvfb-action@v1
      with:
         run: mvn verify -B -Pproduct -Psdk -Ptest --fail-at-end -T4
