# This is a basic workflow to help you get started with Actions

name: publish-docs-gh-pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Maven repository caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Load dependencies with pom-libs.xml
        run: mvn -B install --file pom-libs.xml
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            sphinx==1.8.5
      - name: Build docs with sphinx
        run: mvn install -B -f docs/pom.xml -Dtycho.mode=maven -Pdocs
      - name: Publish Latest user-docs to github pages
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          SRC_FOLDER: docs/target/user/en/html
          DEST_OWNER: uDig
          DEST_REPO: udig.github.io
          DEST_BRANCH: master
          DEST_FOLDER: docs/latest/user
          DEST_PREDEPLOY_CLEANUP: "rm -rf docs/target/user/en/html/*"
